const themes = document.getElementById("themes");
let currentTheme = "";

if (document.URL.includes("setup.html")) {
  themes.addEventListener("change", (event) => {
    currentTheme = event.target.value;
    const theme = localStorage.setItem("theme", currentTheme);
  });
}

const words = {
  movies: [
    "Avatar",
    "Titanic",
    "Star Wars",
    "Jurassic Park",
    "Inception",
    "The Matrix",
    "Pulp Fiction",
    "Gladiator",
    "The Godfather",
    "Fight Club",
    "Braveheart",
    "The Lord of the Rings",
    "The Dark Knight",
    "The Incredibles",
    "Home Alone",
    "Jaws",
    "E.T.",
    "Terminator",
    "Rocky",
    "Casablanca",
    "Jurassic World",
    "Harry Potter",
    "The Avengers",
    "The Lion King",
    "Finding Nemo",
    "Peter Pan",
    "Superman",
    "Batman",
    "Iron Man",
    "Spider-Man",
    "Frozen",
    "Moana",
    "Beauty and the Beast",
    "Cinderella",
    "Aladdin",
    "Mulan",
    "The Little Mermaid",
    "The Green Mile",
    "The Shining",
    "Alien",
    "Back to the Future",
    "Sharknado",
    "Finding Dory",
    "Shark Tale",
    "The Silence of the Lambs",
    "The Exorcist",
    "The Terminator",
    "The Grand Budapest Hotel",
    "The Departed",
    "Forrest Gump",
    "Saving Private Ryan",
    "The Godfather",
    "Pulp Fiction",
    "The Shawshank Redemption",
    "The Dark Knight",
    "The Avengers",
    "The Lion King",
    "Finding Nemo",
    "Toy Story",
    "The Matrix",
    "The Sixth Sense",
    "The Shining",
    "Jurassic Park",
    "Jurassic World",
    "Home Alone",
    "E.T. the Extra-Terrestrial",
    "The Wizard of Oz",
    "Casablanca",
    "Gone with the Wind",
    "Star Wars",
    "Indiana Jones",
    "A Fistful of Dollars",
    "For a Few Dollars More",
    "Apocalypse Now",
    "Taxi Driver",
    "Raging Bull",
    "Goodfellas",
    "The Wolf of Wall Street",
    "Scarface",
    "The Revenant",
    "The Great Gatsby",
    "American Psycho",
    "The Social Network",
    "Fight Club",
    "The Sixth Sense",
    "Unbreakable",
    "Split",
    "Glass",
    "The Happening",
    "Lady in the Water",
    "Signs",
    "The Village",
    "The Visit",
  ],
  famousPeople: [
    "Albert Einstein",
    "Leonardo da Vinci",
    "Nelson Mandela",
    "Abraham Lincoln",
    "Winston Churchill",
    "Mother Teresa",
    "Mahatma Gandhi",
    "Martin Luther King Jr.",
    "Marilyn Monroe",
    "Pablo Picasso",
    "Charles Darwin",
    "Steve Jobs",
    "Elvis Presley",
    "John F. Kennedy",
    "Vincent van Gogh",
    "Beethoven",
    "Frida Kahlo",
    "Michael Jackson",
    "Frank Sinatra",
    "Audrey Hepburn",
    "Amelia Earhart",
    "Mark Twain",
    "William Shakespeare",
    "Cleopatra",
    "George Washington",
    "Queen Elizabeth II",
    "Bob Marley",
    "J.K. Rowling",
    "Pope Francis",
    "Marie Curie",
    "Dalai Lama",
    "Oprah Winfrey",
    "Walt Disney",
    "Muhammad Ali",
    "Charlie Chaplin",
    "George Orwell",
    "Napoleon Bonaparte",
    "John Lennon",
    "Vincent Price",
    "Katharine Hepburn",
    "Walt Whitman",
    "Sigmund Freud",
    "Isaac Newton",
    "Bill Gates",
    "George Clooney",
    "Angelina Jolie",
    "Marlon Brando",
    "Princess Diana",
    "Malala Yousafzai",
    "Elon Musk",
    "Leonardo DiCaprio",
    "Mao Zedong",
    "Wolfgang Amadeus Mozart",
    "Jimi Hendrix",
    "Pele",
    "Marie Antoinette",
    "Charlie Sheen",
    "Pierre Curie",
    "Helen Keller",
    "J.R.R. Tolkien",
    "Ludwig van Beethoven",
    "Benjamin Franklin",
    "James Dean",
    "Albert Schweitzer",
    "Billie Holiday",
    "Henry Ford",
    "Fidel Castro",
    "Grace Kelly",
    "Eleanor Roosevelt",
    "Mae West",
  ],
  countriesCities: [
    "United States",
    "United Kingdom",
    "France",
    "Germany",
    "Italy",
    "Spain",
    "Canada",
    "Japan",
    "Australia",
    "China",
    "India",
    "Brazil",
    "Russia",
    "Mexico",
    "South Africa",
    "Egypt",
    "Greece",
    "Argentina",
    "Turkey",
    "Thailand",
    "South Korea",
    "New Zealand",
    "Sweden",
    "Netherlands",
    "Switzerland",
    "Austria",
    "Belgium",
    "Norway",
    "Denmark",
    "Finland",
    "Ireland",
    "Portugal",
    "Czech Republic",
    "Poland",
    "Hungary",
    "Singapore",
    "Malaysia",
    "Vietnam",
    "Mumbai",
    "Sydney",
    "Rio de Janeiro",
    "Cairo",
    "Athens",
    "Buenos Aires",
    "Istanbul",
    "Bangkok",
    "Seoul",
    "Auckland",
    "Stockholm",
    "Rome",
    "San Francisco",
    "Los Angeles",
    "New York",
    "Paris",
    "London",
    "Berlin",
    "Madrid",
    "Toronto",
    "Tokyo",
    "Sydney",
    "Shanghai",
    "Mumbai",
    "Delhi",
    "Moscow",
    "Cape Town",
    "Cairo",
    "Athens",
    "Buenos Aires",
    "Sao Paulo",
    "Istanbul",
    "Prague",
    "Warsaw",
    "Budapest",
    "Vienna",
    "Brussels",
    "Oslo",
    "Copenhagen",
    "Helsinki",
    "Dublin",
    "Lisbon",
    "Krakow",
    "Bucharest",
    "Kuala Lumpur",
    "Hanoi",
    "Dubai",
    "Beijing",
    "Shanghai",
    "Seoul",
    "Auckland",
    "Stockholm",
    "Amsterdam",
    "Zurich",
    "Geneva",
    "Munich",
    "Barcelona",
    "Milan",
    "Vienna",
    "Prague",
    "Budapest",
    "Warsaw",
    "Bratislava",
    "Ljubljana",
    "Dubrovnik",
    "Montevideo",
    "Caracas",
  ],
  fictionalCharacters: [
    "Harry Potter",
    "Sherlock Holmes",
    "Frodo Baggins",
    "Hermione Granger",
    "Aragorn",
    "Jon Snow",
    "Darth Vader",
    "Luke Skywalker",
    "Frodo Baggins",
    "Bilbo Baggins",
    "Gandalf",
    "Arya Stark",
    "Hannibal Lecter",
    "Dobby",
    "Katniss Everdeen",
    "Hobbit",
    "Spider-Man",
    "Batman",
    "Superman",
    "Wonder Woman",
    "Gollum",
    "Dracula",
    "Sherlock Holmes",
    "Voldemort",
    "Gandalf",
    "Captain Jack Sparrow",
    "Aragorn",
    "Legolas",
    "Hannibal Lecter",
    "Hermione Granger",
    "Hobbit",
    "Darth Vader",
    "Luke Skywalker",
    "Jon Snow",
    "Arya Stark",
    "Dracula",
    "Spider-Man",
    "Batman",
    "Superman",
    "Wonder Woman",
    "Harry Potter",
    "Katniss Everdeen",
    "Gollum",
    "Dobby",
    "Voldemort",
    "Captain Jack Sparrow",
    "Legolas",
    "Bilbo Baggins",
    "Frodo Baggins",
  ],
  dictionary: [
    "aberration",
    "benevolent",
    "cynosure",
    "deleterious",
    "ebullient",
    "facetious",
    "gregarious",
    "histrionic",
    "iconoclast",
    "juxtapose",
    "kaleidoscope",
    "labyrinthine",
    "mellifluous",
    "nepotism",
    "obfuscate",
    "paragon",
    "quixotic",
    "recumbentibus",
    "serendipity",
    "taciturn",
    "ubiquitous",
    "vexatious",
    "wanderlust",
    "xenophobe",
    "yesterday",
    "zeitgeist",
    "acquiesce",
    "bivouac",
    "cachinnate",
    "deipnosophist",
    "effervescent",
    "floccinaucinihilipilification",
    "gobbledygook",
    "hullabaloo",
    "ineffable",
    "juxtaposition",
    "kaleidoscope",
    "loquacious",
    "magnanimous",
    "nomenclature",
    "obfuscate",
    "penultimate",
    "quintessential",
    "recumbentibus",
    "serendipity",
    "tenebrous",
    "ubiquitous",
    "vociferous",
    "winsome",
    "xenophobe",
    "yearning",
    "zeitgeist",
    "antithesis",
    "benevolent",
    "cynosure",
    "deleterious",
    "effervescent",
    "facetious",
    "gregarious",
    "histrionic",
    "iconoclast",
    "juxtapose",
    "kaleidoscope",
    "labyrinthine",
    "mellifluous",
    "nepotism",
    "obfuscate",
    "paragon",
    "quixotic",
    "recumbentibus",
    "serendipity",
    "taciturn",
    "ubiquitous",
    "vexatious",
    "wanderlust",
    "xenophobe",
    "yesterday",
    "zeitgeist",
    "aberration",
    "benevolent",
    "cynosure",
    "deleterious",
    "ebullient",
    "facetious",
    "gregarious",
    "histrionic",
    "iconoclast",
    "juxtapose",
    "kaleidoscope",
    "labyrinthine",
    "mellifluous",
    "nepotism",
    "obfuscate",
    "paragon",
    "quixotic",
    "recumbentibus",
    "serendipity",
    "taciturn",
    "ubiquitous",
    "vexatious",
    "wanderlust",
    "xenophobe",
    "yesterday",
    "zeitgeist",
    "acquiesce",
    "bivouac",
    "cachinnate",
    "deipnosophist",
    "effervescent",
    "floccinaucinihilipilification",
    "gobbledygook",
    "hullabaloo",
    "ineffable",
    "juxtaposition",
    "kaleidoscope",
    "loquacious",
    "magnanimous",
    "nomenclature",
    "obfuscate",
    "penultimate",
    "quintessential",
    "recumbentibus",
    "serendipity",
    "tenebrous",
    "ubiquitous",
    "vociferous",
    "winsome",
    "xenophobe",
    "yearning",
    "zeitgeist",
  ],
};

export function randomWordGenerator() {
  const theme = localStorage.getItem("theme");
  const generatedWord =
    words[theme][Math.floor(Math.random() * words[theme].length)];
  console.log(generatedWord);
  return generatedWord;
}
