const themes = document.getElementById("themes");
let currentTheme = "movies";

if (document.URL.includes("setup.html")) {
  themes.addEventListener("change", (event) => {
    currentTheme = event.target.value;
    console.log(currentTheme);
  });
}

const words = {
  movies: [
    "avatar",
    "titanic",
    "starwars",
    "jurassicpark",
    "inception",
    "matrix",
    "pulpfiction",
    "gladiator",
    "forrestgump",
    "shawshankredemption",
    "thegodfather",
    "fightclub",
    "braveheart",
    "goodfellas",
    "lordoftherings",
    "thedarkknight",
    "incredibles",
    "homealone",
    "jaws",
    "et",
    "terminator",
    "rocky",
    "casablanca",
    "schindlerslist",
    "jurassicworld",
    "harrypotter",
    "avengers",
    "thelionking",
    "findingnemo",
    "peterpan",
    "superman",
    "batman",
    "ironman",
    "spiderman",
    "frozen",
    "moana",
    "beautyandthebeast",
    "cinderella",
    "aladdin",
    "mulan",
    "thelittlemermaid",
    "thegreenmile",
    "theshining",
    "poltergeist",
    "alien",
    "aliens",
    "alienresurrection",
    "prometheus",
    "aliencovenant",
    "backtothefuture",
    "backtothefuture2",
    "backtothefuture3",
    "sharknado",
    "findingdory",
    "sharktale",
    "thelionking",
    "thelionking2",
    "peterpan",
    "superman",
    "batman",
    "ironman",
    "spiderman",
    "frozen",
    "moana",
    "beautyandthebeast",
    "cinderella",
    "aladdin",
    "mulan",
    "thelittlemermaid",
    "thegreenmile",
    "theshining",
    "poltergeist",
    "alien",
    "aliens",
    "alienresurrection",
    "prometheus",
    "aliencovenant",
    "backtothefuture",
    "sharknado",
    "findingdory",
    "sharktale",
    "backtothefuture",
    "backtothefuture2",
    "backtothefuture3",
    "sharknado",
    "findingdory",
    "sharktale",
  ],
  famousPeople: [
    "Albert Einstein",
    "Leonardo da Vinci",
    "Nelson Mandela",
    "Abraham Lincoln",
    "Winston Churchill",
    "Mother Teresa",
    "Mahatma Gandhi",
    "Martin Luther King Jr.",
    "Marilyn Monroe",
    "Pablo Picasso",
    "Charles Darwin",
    "Steve Jobs",
    "Elvis Presley",
    "John F. Kennedy",
    "Vincent van Gogh",
    "Beethoven",
    "Frida Kahlo",
    "Michael Jackson",
    "Frank Sinatra",
    "Audrey Hepburn",
    "Amelia Earhart",
    "Mark Twain",
    "William Shakespeare",
    "Cleopatra",
    "George Washington",
    "Queen Elizabeth II",
    "Bob Marley",
    "J.K. Rowling",
    "Pope Francis",
    "Marie Curie",
    "Dalai Lama",
    "Oprah Winfrey",
    "Walt Disney",
    "Muhammad Ali",
    "Charlie Chaplin",
    "George Orwell",
    "Napoleon Bonaparte",
    "John Lennon",
    "Vincent Price",
    "Katharine Hepburn",
    "Walt Whitman",
    "Sigmund Freud",
    "Isaac Newton",
    "Bill Gates",
    "George Clooney",
    "Angelina Jolie",
    "Marlon Brando",
    "Princess Diana",
    "Malala Yousafzai",
    "Elon Musk",
    "Leonardo DiCaprio",
    "Mao Zedong",
    "Wolfgang Amadeus Mozart",
    "Jimi Hendrix",
    "Pele",
    "Marie Antoinette",
    "Charlie Sheen",
    "Pierre Curie",
    "Helen Keller",
    "J.R.R. Tolkien",
    "Ludwig van Beethoven",
    "Benjamin Franklin",
    "James Dean",
    "Albert Schweitzer",
    "Billie Holiday",
    "Henry Ford",
    "Fidel Castro",
    "Grace Kelly",
    "Eleanor Roosevelt",
    "Mae West",
  ],
};
console.log(words.movies[0]);
export function randomWordGenerator() {
  const generatedWord =
    words.currentTheme[Math.floor(Math.random() * words.currentTheme.length)];
  console.log(generatedWord);
  return generatedWord;
}
